### ISSUE TITLE
Ошибка при запуске монитора пользователей

### ISSUE THREAD

**Issue by namelessnkz** [dxbit/dataexpress#2]
Добрый день. При работе с удаленной базой и попытке запустить монитор пользователей, программа закрывается с ошибкой EDatabaseError, Filedtype Unknown is not supported. Поэтому не получается, к примеру, снять блокировку записи, если в процессе ее редактирования программа аварийно закрылась.

**Comment by dxbit** [comment]
Вы не настроили режим совместимости с Firebird 2.5. Подробнее в вики: https://wiki.mydataexpress.ru/stati:install_fb5_windows#nastrojka_servera

**Comment by namelessnkz** [comment]
Да, действительно не обратил внимания на эти настройки. Помогло, спасибо большое!
